# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('show_only_if_in_resel', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_fr', models.CharField(max_length=64, null=True, unique=True)),
                ('name_en', models.CharField(max_length=64, null=True, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('description_fr', models.CharField(max_length=255, null=True)),
                ('description_en', models.CharField(max_length=255, null=True)),
                ('url', models.URLField()),
                ('fa_icon_name', models.CharField(blank=True, max_length=64)),
                ('glyphicon_name', models.CharField(blank=True, max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Lien',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='article',
            name='glyphicon_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='show_only_if_in_resel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='nbToDisplay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Category'),
        ),
    ]
