# Generated by Django 2.2.24 on 2022-05-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_link_icon_addition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, default='../static/images/icons/placeholder.png', upload_to='image/service_icons'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, default='../static/images/icons/placeholder.png', upload_to='image/service_icons'),
        ),
    ]
