# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170320_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, upload_to='image/service_icons'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, upload_to='image/service_icons'),
        ),
    ]
