# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20170320_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, default='static/images/icons/placeholder.png', upload_to='image/service_icons'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, default='static/images/icons/placeholder.png', upload_to='image/service_icons'),
        ),
    ]
