# TODO: refactor configuration (username, pass...)
# TODO: do not delete migrations

image: docker.resel.fr/myresel:latest  # Custom image made for the ResEl
services:
  - redis:latest
  - mysql/mysql-server:5.5

stages:
  - docker_build
  - docker_push
  - configure
  - test
  - deploy
  
Build docker image:
  stage: docker_build
  services: 
    - docker:dind
  image: docker:stable
  before_script: &before_script
    - docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - docker build -t $image:$CI_COMMIT_SHA .
    - docker push $image:$CI_COMMIT_SHA
  only:
   changes:
     - Dockerfile


Push docker image:
  stage: docker_push
  services:
    - docker:dind
  image: docker:stable
  before_script: *before_script
  script:
    - docker pull $image:$CI_COMMIT_SHA
    - docker tag $image:$CI_COMMIT_SHA $IMAGE:latest
    - docker push $image:latest
  only:
   changes:
     - Dockerfile

variables:
  MYSQL_HOST: mysql-mysql-server
  MYSQL_USER: resel
  MYSQL_PASSWORD: blah
  MYSQL_DATABASE: resel
  MYSQL_ROOT_PASSWORD: blah
  MYSQL_ROOT_HOST: '%'

  REDIS_HOST: redis

  MYSQL_QOS_DATABASE: qos
  MYSQL_QOS_HOST: mysql-mysql-server
  MYSQL_QOS_USER: root
  MYSQL_QOS_PASSWORD: blah
  
  ROOTDIR: ./
  CONFDIR: myresel/
  ETCDIR: .install/etc/
  LIBDIR: .install/lib/
  LDAP_PASSWORD: blah

  LAPUTEX_HOST: http:\/\/laputex.adm.resel.fr\/
# LAPUTEX_PWD in gitlab secrets 

  DEBIAN_FRONTEND: noninteractive

before_script:
  - source .install/scripts/install_essentials.sh no-upgrade
  - apt-get install -qq mysql-client
  - echo "CREATE DATABASE ${MYSQL_QOS_DATABASE}" | mysql -u${MYSQL_QOS_USER} -p${MYSQL_QOS_PASSWORD} -h ${MYSQL_QOS_HOST}
  - source .install/scripts/install_openldap.sh
#  - source .install/scripts/install_latex.sh
  - pip3 install -qUr requirements.txt
  - rm -f -- ${ROOTDIR}myresel/settings_local.py
  - export MYSQL_USER=root
  - source .install/scripts/configure.sh
  - source .install/scripts/populate_db.sh
  - python3 manage.py populate_redis
  - python3 manage.py calculate_free_ip
  - python3 manage.py rqworker &
  - python3 manage.py rqscheduler &

django test suite:
  artifacts:
    paths:
      - htmlcov/
      - myresel/settings_local.py
      - wiki/migrations/
      - tresorerie/migrations/
      - pages/migrations/
      - gestion_personnes/migrations/
      - devices/migrations/
  stage: test
  script:
    - coverage run --rcfile=.coveragerc manage.py test --noinput
    - coverage report
    - coverage html
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'

python linting:
  stage: test
  script:
    - pylint --rcfile=.pylintrc campus devices fonctions gestion_personnes ldapback myresel pages tresorerie wiki || exit $((35 & $?))
  allow_failure: false

deploy to staging:
  services: []
  before_script:
    - apt-get install -qq openssh-client
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "${STAGING_DEPLOY_KEY}")'
  stage: deploy
  script:
    - ssh -o "StrictHostKeyChecking=no" -T deploy@flea.adm
  only:
    - master
  environment:
    name: staging flea
    url: https://dev.resel.fr/

deploy to brest:
  services: []
  before_script:
    - apt-get install -qq openssh-client
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "${SKYNET_DEPLOY_KEY}")'
  stage: deploy
  script:
    - ssh -o "StrictHostKeyChecking=no" -T deploy@skynet.adm
  only:
    - deploy
  environment:
    name: skynet
    url: https://resel.fr/

deploy to rennes:
  services: []
  before_script:
    - apt-get install -qq openssh-client
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "${DOUBIDOU_DEPLOY_KEY}")'
  stage: deploy
  script:
    - ssh -o "StrictHostKeyChecking=no" -T deploy@doubidou.adm
  only:
    - deploy
  environment:
    name: doubidou
    url: https://rennes.resel.fr/
