# TODO: refactor configuration (username, pass...)
# TODO: do not delete migrations

image: docker.resel.fr/web:latest  # Custom image made for the ResEl
services:
  - redis:latest
  - mysql/mysql-server:5.5

stages:
  - configure
  - test
  - deploy

variables:
  MYSQL_HOST: mysql-mysql-server
  MYSQL_USER: resel
  MYSQL_PASSWORD: blah
  MYSQL_DATABASE: resel
  MYSQL_ROOT_PASSWORD: blah
  MYSQL_ROOT_HOST: '%'

  REDIS_HOST: redis

  MYSQL_QOS_DATABASE: qos
  MYSQL_QOS_HOST: mysql-mysql-server
  MYSQL_QOS_USER: root
  MYSQL_QOS_PASSWORD: blah
  
  ROOTDIR: ./
  CONFDIR: myresel/
  ETCDIR: .install/etc/
  LIBDIR: .install/lib/
  LDAP_PASSWORD: blah

  LAPUTEX_HOST: http:\/\/laputex.adm.resel.fr\/
# LAPUTEX_PWD in gitlab secrets 

  DEBIAN_FRONTEND: noninteractive

before_script:
  - source .install/scripts/install_essentials.sh no-upgrade
  - apt-get install -qq mysql-client
  - echo "CREATE DATABASE ${MYSQL_QOS_DATABASE}" | mysql -u${MYSQL_QOS_USER} -p${MYSQL_QOS_PASSWORD} -h ${MYSQL_QOS_HOST}
  - source .install/scripts/install_openldap.sh
#  - source .install/scripts/install_latex.sh
  - pip3 install -qUr requirements.txt
  - rm -f -- ${ROOTDIR}myresel/settings_local.py
  - export MYSQL_USER=root
  - source .install/scripts/configure.sh
  - source .install/scripts/populate_db.sh
  - python3 manage.py populate_redis
  - python3 manage.py calculate_free_ip
  - python3 manage.py rqworker &
  - python3 manage.py rqscheduler &

test_django:
  artifacts:
    paths:
      - htmlcov/
      - myresel/settings_local.py
      - wiki/migrations/
      - tresorerie/migrations/
      - pages/migrations/
      - gestion_personnes/migrations/
      - devices/migrations/
  stage: test
  script:
    - coverage run --rcfile=.coveragerc manage.py test --noinput
    - coverage report
    - coverage html
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'

pylint:
  stage: test
  script:
    - pip3 install pylint --quiet
    - pip3 install pylint-django --quiet --upgrade
    - pylint --rcfile=.pylintrc campus devices fonctions gestion_personnes ldapback myresel pages tresorerie wiki || exit $((35 & $?))
  allow_failure: false

deploy staging:
  services: []
  before_script:
    - echo ${STAGING_DEPLOY_KEY} > id_rsa
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no -i id_rsa -T deploy@flea.adm
  only:
    - master
  environment:
    name: staging flea
    url: https://dev.resel.fr/

deploy to brest:
  services: []
  before_script:
    - apt-get -qq install curl
  stage: deploy
  script:
    - curl http://skynet.adm.resel.fr/deploy-resel
  only:
    - deploy
  environment:
    name: skynet
    url: https://resel.fr/

deploy to rennes:
  services: []
  before_script:
    - apt-get -qq install curl
  stage: deploy
  script:
    - curl http://doubidou.adm.resel.fr/deploy-resel
  only:
    - deploy
  environment:
    name: doubidou
    url: https://rennes.resel.fr/
