# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleData',
            fields=[
                ('site', models.CharField(db_column='site', default=None, editable=False, max_length=32)),
                ('cn', models.CharField(db_column='cn', default=None, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_column='uid', default=None, editable=False, max_length=16)),
                ('way', models.CharField(choices=[('up', 'up'), ('down', 'down')], db_column='way', default=None, editable=False, max_length=4)),
                ('flow', models.CharField(choices=[('clean', 'clean'), ('dirty', 'dirty')], db_column='flow', default=None, editable=False, max_length=5)),
                ('group', models.IntegerField(db_column='group', default=None, editable=False)),
                ('amount', models.BigIntegerField(db_column='amount', default=None, editable=False)),
                ('amount_ponderated', models.BigIntegerField(db_column='amount_ponderated', default=None, editable=False)),
                ('last_rate', models.IntegerField(db_column='last_rate', default=None, editable=False)),
            ],
            options={
                'db_table': 'people_data',
                'default_permissions': (),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleHistory',
            fields=[
                ('site', models.CharField(db_column='site', default=None, editable=False, max_length=32)),
                ('timestamp', models.IntegerField(db_column='timestamp', default=None, editable=False)),
                ('cn', models.CharField(db_column='cn', default=None, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_column='uid', default=None, editable=False, max_length=16)),
                ('way', models.CharField(choices=[('up', 'up'), ('down', 'down')], db_column='way', default=None, editable=False, max_length=4)),
                ('flow', models.CharField(choices=[('clean', 'clean'), ('dirty', 'dirty')], db_column='flow', default=None, editable=False, max_length=5)),
                ('group', models.IntegerField(db_column='group', default=None, editable=False)),
                ('amount', models.BigIntegerField(db_column='amount', default=None, editable=False)),
                ('amount_ponderated', models.BigIntegerField(db_column='amount_ponderated', default=None, editable=False)),
                ('duration', models.IntegerField(db_column='duration', default=None, editable=False)),
            ],
            options={
                'db_table': 'people_history',
                'default_permissions': (),
                'managed': False,
            },
        ),
    ]
