# Generated by Django 2.2.24 on 2021-07-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeopleData',
        ),
        migrations.DeleteModel(
            name='PeopleHistory',
        ),
    ]
