# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 17:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('titre_fr', models.CharField(max_length=100, null=True)),
                ('titre_en', models.CharField(max_length=100, null=True)),
                ('contenu', ckeditor.fields.RichTextField()),
                ('contenu_fr', ckeditor.fields.RichTextField(null=True)),
                ('contenu_en', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'verbose_name': 'news',
            },
        ),
    ]
