# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 00:05
from __future__ import unicode_literals

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_text_fr', models.CharField(max_length=200, null=True)),
                ('question_text_en', models.CharField(max_length=200, null=True)),
                ('response', ckeditor.fields.RichTextField()),
                ('response_fr', ckeditor.fields.RichTextField(null=True)),
                ('response_en', ckeditor.fields.RichTextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('vote', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
