# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 23:15
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='contenu_en',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='contenu_fr',
            new_name='content_fr',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='titre_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='titre_fr',
            new_name='title_fr',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 4, 23, 15, 16, 670006, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
