# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='moderated_by',
            field=models.CharField(editable=False, max_length=127, verbose_name='Modéré par'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.CharField(max_length=127, verbose_name='Envoyeur'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=127, verbose_name='Sujet'),
        ),
    ]
