# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus', '0002_roomadmin_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomadmin',
            name='uid',
        ),
        migrations.AddField(
            model_name='roomadmin',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
            preserve_default=False,
        ),
    ]
