# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('campus', '0003_auto_20161209_1431'), ('campus', '0004_auto_20161209_1627'), ('campus', '0005_auto_20170126_1456'), ('campus', '0006_auto_20170126_1456')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campus', '0002_roomadmin_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomadmin',
            name='uid',
        ),
        migrations.AddField(
            model_name='roomadmin',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='room',
            name='allowed_members',
        ),
        migrations.AddField(
            model_name='room',
            name='clubs',
            field=models.TextField(blank=True, help_text='indique à quel(s) club(s) appartient la salle, un par ligne', verbose_name='club(s)'),
        ),
        migrations.DeleteModel(
            name='MailModerator',
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={},
        ),
        migrations.AddField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de réception'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.CharField(max_length=15, verbose_name='Envoyeur'),
        ),
    ]
