# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_update_mail_max_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='name',
            field=models.TextField(default='Evenement', help_text="nom de l'évènement"),
        ),
        migrations.AlterField(
            model_name='room',
            name='clubs',
            field=models.TextField(blank=True, help_text='indique à quel(s) club(s) appartient la salle, séparés par un point virgule ;', verbose_name='club(s)'),
        ),
    ]
