# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20161209_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='allowed_members',
        ),
        migrations.AddField(
            model_name='room',
            name='clubs',
            field=models.TextField(blank=True, help_text='indique à quel(s) club(s) appartient la salle', verbose_name='club(s)'),
        ),
    ]
