# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_auto_20161209_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailModerator',
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={},
        ),
        migrations.AddField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 26, 14, 56, 13, 897563), editable=False, verbose_name='Date de réception'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.CharField(max_length=15, verbose_name='Envoyeur'),
        ),
        migrations.AlterField(
            model_name='room',
            name='clubs',
            field=models.TextField(blank=True, help_text='indique à quel(s) club(s) appartient la salle, un par ligne', verbose_name='club(s)'),
        ),
    ]
