# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_auto_20170126_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de réception'),
        ),
    ]
