# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 11:11
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetaData',
            fields=[
                ('uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email_validation_code', models.UUIDField(default=uuid.uuid4)),
                ('email_validated', models.BooleanField(default=False)),
                ('reset_pwd_code', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]

