# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# tresorerie.migrations.0010_version2_populate

class Migration(migrations.Migration):

    replaces = [('tresorerie', '0001_version1'), ('tresorerie', '0009_version2_create'), ('tresorerie', '0010_version2_populate'), ('tresorerie', '0011_version2_finalize'), ('tresorerie', '0012_auto_20160926_1046')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(blank=True, max_length=50)),
                ('moyen', models.CharField(choices=[('L', 'Liquide'), ('C', 'Chèque'), ('CB', 'Carte bancaire')], max_length=2, verbose_name='moyen de paiement')),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.FloatField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('admin', models.CharField(default='resel.fr', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('months_to_pay', models.IntegerField()),
                ('months_paid', models.IntegerField(default=0)),
                ('customer', models.CharField(max_length=50)),
                ('last_paid', models.DateField(default=django.utils.timezone.now)),
                ('amount_to_pay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'banque',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numéro')),
                ('nom', models.CharField(max_length=100)),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="date d'émission")),
                ('montant', models.FloatField()),
                ('encaisse', models.BooleanField(default=False, editable=False, verbose_name='encaissé')),
                ('date_encaissement', models.DateField(blank=True, null=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresorerie.Bank')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tresorerie.Transaction')),
            ],
            options={
                'verbose_name': 'chèque',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('type_produit', models.CharField(choices=[('A', 'Adhésion'), ('M', 'Matériel'), ('F', "Frais d'accès")], max_length=1, verbose_name='type de produit')),
                ('duree', models.IntegerField(blank=True, help_text="durée en mois des frais d'accès (si type = frais d'accès, laisser vide sinon)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='durée')),
                ('autorisation', models.CharField(choices=[('FIG', 'FIG'), ('FIP', 'FIP'), ('ALL', 'ALL')], default='ALL', help_text='Définit qui est éligible à ce produit', max_length=3, verbose_name="Authorisation d'achat")),
            ],
            options={
                'verbose_name': 'produit',
            },
        ),
        migrations.AlterModelOptions(
            name='monthlypayment',
            options={'verbose_name': 'paiement mensuel', 'verbose_name_plural': 'paiements mensuels'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='produit',
            field=models.ManyToManyField(to='tresorerie.Product'),
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('ldap_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stripe_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='admin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='facture',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin de la facture en pdf'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('A', 'En attente'), ('N', 'Non payée'), ('P', 'Payée'), ('E', 'Erreur')], default='N', max_length=3, verbose_name='Statut de la transaction'),
        ),
    ]
