# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 08:34
from __future__ import unicode_literals

import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('tresorerie', 'Transaction')
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0009_version2_create'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
