# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 22:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0012_auto_20160926_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duree',
            field=models.IntegerField(blank=True, help_text="Durée en mois des frais d'accès (si type = frais d'accès, laisser vide sinon)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='durée'),
        ),
    ]
