# Generated by Django 2.2.24 on 2021-07-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0013_auto_20170203_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tresorerie.Transaction'),
        ),
    ]
